import mongoose from "mongoose";
import auditPlugin from "../plugins/auditPlugin.mjs";

const purchaseBookEntrySchema = new mongoose.Schema({
  entryNo: { type: String, required: true, unique: true },
  entryDate: { type: String },
  supplierInvNo: { type: String },
  supplierInvDate: { type: String },
  jobNo: { type: String, index: true },
  chargeRef: { type: String, index: true },
  jobRef: { type: String, index: true },
  supplierName: { type: String },
  address1: { type: String },
  address2: { type: String },
  address3: { type: String },
  state: { type: String },
  country: { type: String },
  pinCode: { type: String },
  registrationType: { type: String, default: 'Regular' },
  gstinNo: { type: String, index: true },
  pan: { type: String },
  cin: { type: String },
  placeOfSupply: { type: String },
  creditTerms: { type: String },
  descriptionOfServices: { type: String },
  revenueLedger: { type: String },
  sac: { type: String },
  taxableValue: { type: Number },
  gstPercent: { type: Number },
  cgstAmt: { type: Number },
  sgstAmt: { type: Number },
  igstAmt: { type: Number },
  tds: { type: Number },
  total: { type: Number },
  revenueAmount: { type: Number },
  revenueBasicAmount: { type: Number },
  revenueGstAmount: { type: Number },
  revenueCgst: { type: Number },
  revenueSgst: { type: Number },
  revenueIgst: { type: Number },
  revenueTotal: { type: Number },
  isApproved: { type: Boolean, default: false },
  isPostBilling: { type: Boolean, default: false },
  approvedByFirst: { type: String, trim: true },
  approvedByLast: { type: String, trim: true },
  approvedAt: { type: Date },
  isRejected: { type: Boolean, default: false },
  rejectedByFirst: { type: String, trim: true },
  rejectedByLast: { type: String, trim: true },
  rejectedAt: { type: Date },
  rejectionReason: { type: String },
  utrNumber: { type: String },
  utrAddedBy: { type: String },
  utrAddedAt: { type: Date },
  paymentReceiptUrl: { type: String },
  bankFrom: { type: String },
  attachments: [{ type: String }],
  chargeDescription: { type: String },
  chargeHeading: { type: String },
  chargeHeadCategory: { type: String },
  tdsCategory: { type: String, default: '94C' },
  status: { type: String, default: '' },
  virtualBalanceTerminal: { type: String, default: '' },
  isMultiCharge: { type: Boolean, default: false },
  chargeItems: { type: Array, default: [] },
  chargeRefs: { type: [String], default: [] },
  currency: { type: String, default: 'INR' },
  currencyAmount: { type: Number },
  exchangeRate: { type: Number },
  qty: { type: Number, default: 1 },
  rate: { type: Number, default: 0 },
  etaDate: { type: String, default: '' },
  volumeCbm: { type: String, default: '' },
  igmNo: { type: String, default: '' },
  igmDate: { type: String, default: '' },
  createdAt: { type: Date, default: Date.now }
}, { timestamps: true });

purchaseBookEntrySchema.plugin(auditPlugin, { documentType: "purchaseBookEntry" });

const PurchaseBookEntryModel = mongoose.model(
  "purchaseBookEntry",
  purchaseBookEntrySchema
);

export default PurchaseBookEntryModel;
