export const moduleCategories = {
  Accounts: "Accounts",
  "Import - Billing": "Accounts",
  "Employee Onboarding": "HR & Management",
  "Employee KYC": "HR & Management",
  "Update Employee Data": "HR & Management",
  "Customer KYC": "Customer KYC",
  "Import - DSR": "DSR Module",
  "Audit Trail": "DSR Module",
  "Report": "Analytics & Reports",
  Documentation: "DSR Module",
  Submission: "DSR Module",
  "Import - Operations": "DSR Module",
  "Import - Add": "DSR Module",
  "Import - DO": "DSR Module",
  "e-Sanchit": "DSR Module",
  "Import Utility Tool": "DSR Module",
  "Inward Register": "Inward and Outward Register",
  "Outward Register": "Inward and Outward Register",
  "Exit Feedback": "HR & Management",
  "Export - Directories": "Export",
  "Export - Audit Trail": "Export",
  "Export - Charges": "Export",
  "Export - Documentation": "Export",
  "Export - E-Sanchit": "Export",
  "Export - Jobs": "Export",
  "Export - Operation": "Export",
  "CRM": "CRM",
  "DGFT": "DGFT",
  "Open Points": "Project Management",
  "KPI": "Project Management",
  "MRM": "Project Management",
  "Pulse": "Analytics & Reports",
  "MasterDirectory": "Masters",
};

