export const moduleCategories = {
  Accounts: "Accounts",
  "Import - Billing": "Accounts",
  "Employee Onboarding": "HR & Management",
  "Employee KYC": "HR & Management",
  "Customer KYC": "Customer KYC",
  "Import - DSR": "DSR Module",
  "Audit Trail": "DSR Module",
  "Report": "DSR Module",
  Documentation: "DSR Module",
  Submission: "DSR Module",
  "Import - Operations": "DSR Module",
  "Import - Add": "DSR Module",
  "Import - DO": "DSR Module",
  "e-Sanchit": "DSR Module",
  "Import Utility Tool": "DSR Module",
  "Inward Register": "Inward and Outward Register",
  "Outward Register": "Inward and Outward Register",
  "Exit Feedback": "HR & Management",
  Export: "Export",
  Screen1: "Screens",
  Screen2: "Screens",
  Screen3: "Screens",
  Screen4: "Screens",
  Screen5: "Screens",
  Screen6: "Screens",

  "Open Points": "Project Management",
};

