export const moduleCategories = {
  Accounts: "Accounts",
  "Import - Billing": "Accounts",
  "Employee Onboarding": "HR & Management",
  "Employee KYC": "HR & Management",
  "Customer KYC": "Customer KYC",
  "Import - DSR": "DSR Module",
  Documentation: "DSR Module",
  Submission: "DSR Module",
  "Import - Operations": "DSR Module",
  "Import - Add": "DSR Module",
  "Import - DO": "DSR Module",
  "e-Sanchit": "DSR Module",
  "Import Utility Tool": "DSR Module",
  "LR Operations": "Transportation Module",
  "Inward Register": "Inward and Outward Register",
  "Outward Register": "Inward and Outward Register",
  "Elock-Operation": "Transportation Module",
  "Exit Feedback": "HR & Management",
  "Tyre Maintenance": "Transportation Module",
  Directories: "Directories Mgt.",
  "SR CEL": "Transportation Module",
  "Elock Operation": "Transportation Module",
  RTO: "Transportation Module",
  Export: "Export",
  Screen1: "Screens",
  Screen2: "Screens",
  Screen3: "Screens",
  Screen4: "Screens",
  Screen5: "Screens",
  Screen6: "Screens",
};
