import mongoose from 'mongoose';
import path from 'path';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';

// Import service
import PayrollGenerator from '../services/payroll/payrollCalculation.service.js';
import PayrollRun from '../model/attendance/PayrollRun.js';
import PayrollSummary from '../model/attendance/PayrollSummary.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: path.resolve(__dirname, '../.env') });

const MONGODB_URI = process.env.DEV_MONGODB_URI || process.env.MONGODB_URI || 'mongodb://localhost:27017/exim';

async function verifyPayroll() {
  await mongoose.connect(MONGODB_URI);
  console.log('Connected to DB');

  const companyId = new mongoose.Types.ObjectId("69cd1e3b50e6c73acc73a926"); // RABS
  const ajithId = new mongoose.Types.ObjectId("6937e569b367c7f6e9119342");
  const afzalId = new mongoose.Types.ObjectId("6a059ab3d065f33262fa04fe");

  console.log('\n--- Running Payroll Generation for May 2026 ---');
  const result = await PayrollGenerator.generate({
    companyId: companyId,
    year: 2026,
    month: 5,
    generatedBy: ajithId // generated by HOD Ajith
  });

  console.log('Payroll Run Status:', result.payrollRun.payroll_status);
  console.log('Summaries generated:', result.summaries.length);
  console.log('Errors:', result.errors);

  // Fetch summaries
  const summaries = await PayrollSummary.find({
    payroll_run_id: result.payrollRun._id,
    employee_id: { $in: [ajithId, afzalId] }
  }).populate('employee_id');

  for (const s of summaries) {
    console.log(`\n========================================`);
    console.log(`Employee: ${s.employee_id.first_name} ${s.employee_id.last_name} (${s.employee_id.username})`);
    console.log(`Type: ${s.payroll_type} (Is Operator: ${s.is_operator})`);
    console.log(`----------------------------------------`);
    console.log(`Calendar Days: ${s.total_days_in_month}`);
    console.log(`Present Days: ${s.present_days}`);
    console.log(`Half Days: ${s.half_days}`);
    console.log(`Absent Days: ${s.absent_days}`);
    console.log(`Leave Days: ${s.leave_days}`);
    console.log(`Weekly Offs: ${s.weekly_off_days}`);
    console.log(`Holidays: ${s.holiday_days}`);
    console.log(`Payable Days: ${s.payable_days}`);
    console.log(`----------------------------------------`);
    console.log(`Total Regular Hours: ${s.total_regular_hours}`);
    console.log(`Total Overtime Hours: ${s.total_overtime_hours}`);
    console.log(`----------------------------------------`);
    console.log(`Basic Snapshot (Monthly/Daily): ${s.payroll_type === 'MONTHLY' ? s.monthly_salary_snapshot : s.daily_wage_snapshot}`);
    console.log(`OT Rate Snapshot: ${s.ot_rate_snapshot || '(computed: daily_wage/8 or monthly/248)'}`);
    console.log(`Basic Amount Calculated: ${s.basic_amount}`);
    console.log(`Overtime Amount Calculated: ${s.overtime_amount}`);
    console.log(`Net Payable Amount: ${s.net_payable_amount}`);
    console.log(`========================================`);
  }

  await mongoose.disconnect();
}

verifyPayroll().catch(console.error);
